# Generated by Django 6.0 on 2025-12-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has application-level admin access.",
            ),
        ),
    ]
