# Generated by Django 6.0 on 2025-12-09 19:45

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


def migrate_admins(apps, schema_editor):
    User = apps.get_model("users", "User")
    Administrator = apps.get_model("users", "Administrator")
    admin_users = User.objects.filter(is_admin=True)
    for user in admin_users:
        Administrator.objects.create(user=user, level=1)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            code=migrate_admins,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
