# Generated by Django 6.0 on 2025-12-23 03:50

from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F, Q


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adventure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_template", models.BooleanField(default=False)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("intro", models.TextField(blank=True)),
                ("spec_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="authored_adventures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="played_adventures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_adventure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="runs",
                        to="adventures.adventure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=Q(("is_template", False)),
                        fields=["player_user"],
                        name="idx_adventures_player",
                    ),
                    models.Index(fields=["is_template"], name="idx_adventures_template"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            (
                                Q(("is_template", True))
                                & Q(("player_user__isnull", True))
                                & Q(("template_adventure__isnull", True))
                            )
                            | (
                                Q(("is_template", False))
                                & Q(("player_user__isnull", False))
                                & Q(("template_adventure__isnull", False))
                            )
                        ),
                        name="adventures_template_or_run_chk",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_feature", models.TextField(choices=[("body", "body"), ("mind", "mind"), ("will", "will")])),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("tags", ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abilities",
                        to="adventures.adventure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    GinIndex(fields=["tags"], name="idx_abilities_tags_gin"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(("base_feature__in", ["body", "mind", "will"])),
                        name="abilities_base_feature_chk",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Faction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("tags", ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factions",
                        to="adventures.adventure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    GinIndex(fields=["tags"], name="idx_factions_tags_gin"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("x", models.IntegerField(default=0)),
                ("y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=1)),
                ("height", models.IntegerField(default=1)),
                ("tags", ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="adventures.adventure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure", "x", "y"], name="idx_locations_adv_xy"),
                    GinIndex(fields=["tags"], name="idx_locations_tags_gin"),
                ],
                "constraints": [
                    models.CheckConstraint(condition=Q(("width__gt", 0)), name="locations_width_gt_zero"),
                    models.CheckConstraint(condition=Q(("height__gt", 0)), name="locations_height_gt_zero"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OtherInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.TextField()),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("tags", ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_infos",
                        to="adventures.adventure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure", "category"], name="idx_other_info_category"),
                    GinIndex(fields=["tags"], name="idx_other_info_tags_gin"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("tags", ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="adventures.adventure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    GinIndex(fields=["tags"], name="idx_races_tags_gin"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdventureHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.TextField(choices=[("user", "user"), ("ai", "ai"), ("system", "system")])),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="adventures.adventure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure", "-id"], name="idx_history_adv_entry_desc"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(("role__in", ["user", "ai", "system"])),
                        name="history_role_chk",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AdventureMemory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.TextField(choices=[("summary", "summary"), ("fact", "fact"), ("rule", "rule"), ("goal", "goal")])),
                ("title", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("importance", models.IntegerField(default=0)),
                ("tags", ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="adventures.adventure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure", "-importance"], name="idx_memories_adv_importance"),
                    GinIndex(fields=["tags"], name="idx_memories_tags_gin"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(("kind__in", ["summary", "fact", "rule", "goal"])),
                        name="memories_kind_chk",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_player", models.BooleanField(default=False)),
                ("title", models.TextField()),
                ("age", models.IntegerField(blank=True, null=True)),
                ("body_power", models.IntegerField(default=0)),
                ("mind_power", models.IntegerField(default=0)),
                ("will_power", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("tags", ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="adventures.adventure",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters",
                        to="adventures.location",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters",
                        to="adventures.race",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure", "location"], name="idx_characters_adv_location"),
                    models.Index(fields=["adventure", "is_player"], name="idx_characters_is_player"),
                    GinIndex(fields=["tags"], name="idx_characters_tags_gin"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(("age__gte", 0)) | Q(("age__isnull", True)),
                        name="characters_age_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=Q(("body_power__gte", 0)),
                        name="characters_body_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=Q(("mind_power__gte", 0)),
                        name="characters_mind_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=Q(("will_power__gte", 0)),
                        name="characters_will_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RaceAbility",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_abilities",
                        to="adventures.ability",
                    ),
                ),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_abilities",
                        to="adventures.adventure",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_abilities",
                        to="adventures.race",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure"], name="idx_races_abilities_adv"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("adventure", "race", "ability"),
                        name="uq_races_abilities",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterAbility",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_abilities",
                        to="adventures.ability",
                    ),
                ),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_abilities",
                        to="adventures.adventure",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_abilities",
                        to="adventures.character",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure"], name="idx_characters_abilities_adv"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("adventure", "character", "ability"),
                        name="uq_characters_abilities",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterFaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_factions",
                        to="adventures.adventure",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_factions",
                        to="adventures.character",
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_factions",
                        to="adventures.faction",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure"], name="idx_characters_factions_adv"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("adventure", "character", "faction"),
                        name="uq_characters_factions",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterRelationship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_relationships",
                        to="adventures.adventure",
                    ),
                ),
                (
                    "from_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="adventures.character",
                    ),
                ),
                (
                    "to_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="adventures.character",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure", "from_character"], name="idx_rel_from"),
                    models.Index(fields=["adventure", "to_character"], name="idx_rel_to"),
                    models.Index(fields=["adventure", "kind"], name="idx_rel_kind"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=~Q(("from_character", F("to_character"))),
                        name="rel_not_self",
                    ),
                    models.UniqueConstraint(
                        fields=("adventure", "from_character", "to_character", "kind"),
                        name="uq_relationship",
                    ),
                ],
            },
        ),
    ]
