# Generated by Django 6.0 on 2025-12-23 05:20

from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


DROP_OLD_TRIGGERS_SQL = """
DROP TRIGGER IF EXISTS trg_races_abilities_same_adventure ON adventures_raceability;
DROP FUNCTION IF EXISTS enforce_race_ability_same_adventure();

DROP TRIGGER IF EXISTS trg_characters_abilities_same_adventure ON adventures_characterability;
DROP FUNCTION IF EXISTS enforce_character_ability_same_adventure();
"""


RESTORE_OLD_TRIGGERS_SQL = """
CREATE OR REPLACE FUNCTION enforce_race_ability_same_adventure()
RETURNS TRIGGER AS $$
DECLARE
    race_adv BIGINT;
    ab_adv   BIGINT;
BEGIN
    SELECT adventure_id INTO race_adv FROM adventures_race WHERE id = NEW.race_id;
    SELECT adventure_id INTO ab_adv   FROM adventures_ability WHERE id = NEW.ability_id;

    IF race_adv IS NULL OR ab_adv IS NULL THEN
        RAISE EXCEPTION 'Race % or ability % not found', NEW.race_id, NEW.ability_id;
    END IF;

    IF NEW.adventure_id <> race_adv OR NEW.adventure_id <> ab_adv THEN
        RAISE EXCEPTION 'Adventure mismatch in races_abilities: row adv %, race adv %, ability adv %',
            NEW.adventure_id, race_adv, ab_adv;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_races_abilities_same_adventure
BEFORE INSERT OR UPDATE ON adventures_raceability
FOR EACH ROW EXECUTE FUNCTION enforce_race_ability_same_adventure();

CREATE OR REPLACE FUNCTION enforce_character_ability_same_adventure()
RETURNS TRIGGER AS $$
DECLARE
    c_adv BIGINT;
    a_adv BIGINT;
BEGIN
    SELECT adventure_id INTO c_adv FROM adventures_character WHERE id = NEW.character_id;
    SELECT adventure_id INTO a_adv FROM adventures_ability   WHERE id = NEW.ability_id;

    IF c_adv IS NULL OR a_adv IS NULL THEN
        RAISE EXCEPTION 'Character % or ability % not found', NEW.character_id, NEW.ability_id;
    END IF;

    IF NEW.adventure_id <> c_adv OR NEW.adventure_id <> a_adv THEN
        RAISE EXCEPTION 'Adventure mismatch in characters_abilities: row adv %, char adv %, ability adv %',
            NEW.adventure_id, c_adv, a_adv;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_characters_abilities_same_adventure
BEFORE INSERT OR UPDATE ON adventures_characterability
FOR EACH ROW EXECUTE FUNCTION enforce_character_ability_same_adventure();
"""


NEW_TRIGGERS_SQL = """
CREATE OR REPLACE FUNCTION enforce_technique_same_adventure_as_system()
RETURNS TRIGGER AS $$
DECLARE
    s_adv BIGINT;
BEGIN
    SELECT adventure_id INTO s_adv FROM adventures_skillsystem WHERE id = NEW.system_id;

    IF s_adv IS NULL THEN
        RAISE EXCEPTION 'System % not found', NEW.system_id;
    END IF;

    IF NEW.adventure_id <> s_adv THEN
        RAISE EXCEPTION 'Adventure mismatch: technique adv %, system adv %', NEW.adventure_id, s_adv;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_techniques_same_adventure_system
BEFORE INSERT OR UPDATE ON adventures_technique
FOR EACH ROW EXECUTE FUNCTION enforce_technique_same_adventure_as_system();

CREATE OR REPLACE FUNCTION enforce_character_system_same_adventure()
RETURNS TRIGGER AS $$
DECLARE
    c_adv BIGINT;
    s_adv BIGINT;
BEGIN
    SELECT adventure_id INTO c_adv FROM adventures_character WHERE id = NEW.character_id;
    SELECT adventure_id INTO s_adv FROM adventures_skillsystem WHERE id = NEW.system_id;

    IF c_adv IS NULL OR s_adv IS NULL THEN
        RAISE EXCEPTION 'Character % or system % not found', NEW.character_id, NEW.system_id;
    END IF;

    IF NEW.adventure_id <> c_adv OR NEW.adventure_id <> s_adv THEN
        RAISE EXCEPTION 'Adventure mismatch in character_systems: row %, char %, system %',
            NEW.adventure_id, c_adv, s_adv;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_character_systems_same_adventure
BEFORE INSERT OR UPDATE ON adventures_charactersystem
FOR EACH ROW EXECUTE FUNCTION enforce_character_system_same_adventure();

CREATE OR REPLACE FUNCTION enforce_character_technique_same_adventure()
RETURNS TRIGGER AS $$
DECLARE
    c_adv BIGINT;
    t_adv BIGINT;
BEGIN
    SELECT adventure_id INTO c_adv FROM adventures_character WHERE id = NEW.character_id;
    SELECT adventure_id INTO t_adv FROM adventures_technique WHERE id = NEW.technique_id;

    IF c_adv IS NULL OR t_adv IS NULL THEN
        RAISE EXCEPTION 'Character % or technique % not found', NEW.character_id, NEW.technique_id;
    END IF;

    IF NEW.adventure_id <> c_adv OR NEW.adventure_id <> t_adv THEN
        RAISE EXCEPTION 'Adventure mismatch in character_techniques: row %, char %, tech %',
            NEW.adventure_id, c_adv, t_adv;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_character_techniques_same_adventure
BEFORE INSERT OR UPDATE ON adventures_charactertechnique
FOR EACH ROW EXECUTE FUNCTION enforce_character_technique_same_adventure();
"""


REVERSE_NEW_TRIGGERS_SQL = """
DROP TRIGGER IF EXISTS trg_character_techniques_same_adventure ON adventures_charactertechnique;
DROP FUNCTION IF EXISTS enforce_character_technique_same_adventure();

DROP TRIGGER IF EXISTS trg_character_systems_same_adventure ON adventures_charactersystem;
DROP FUNCTION IF EXISTS enforce_character_system_same_adventure();

DROP TRIGGER IF EXISTS trg_techniques_same_adventure_system ON adventures_technique;
DROP FUNCTION IF EXISTS enforce_technique_same_adventure_as_system();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0002_consistency_triggers"),
    ]

    operations = [
        migrations.RunSQL(DROP_OLD_TRIGGERS_SQL, RESTORE_OLD_TRIGGERS_SQL),
        migrations.DeleteModel(
            name="CharacterAbility",
        ),
        migrations.DeleteModel(
            name="RaceAbility",
        ),
        migrations.DeleteModel(
            name="Ability",
        ),
        migrations.CreateModel(
            name="SkillSystem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("tags", ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ("w_body", models.IntegerField(default=0)),
                ("w_mind", models.IntegerField(default=0)),
                ("w_will", models.IntegerField(default=0)),
                ("formula_hint", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_systems",
                        to="adventures.adventure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure"], name="idx_skill_systems_adv"),
                    GinIndex(fields=["tags"], name="idx_skill_systems_tags_gin"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(("w_body__gte", 0))
                        & Q(("w_mind__gte", 0))
                        & Q(("w_will__gte", 0)),
                        name="skill_systems_weights_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=Q(("w_body__gt", 0)) | Q(("w_mind__gt", 0)) | Q(("w_will__gt", 0)),
                        name="skill_systems_weights_not_all_zero",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("tags", ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ("difficulty", models.IntegerField(default=0)),
                ("tier", models.IntegerField(default=0)),
                ("required_system_level", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="techniques",
                        to="adventures.adventure",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="techniques",
                        to="adventures.skillsystem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure", "system"], name="idx_techniques_adv_system"),
                    GinIndex(fields=["tags"], name="idx_techniques_tags_gin"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(("difficulty__gte", 0)),
                        name="techniques_difficulty_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=Q(("tier__gte", 0)),
                        name="techniques_tier_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=Q(("required_system_level__gte", 0)),
                        name="techniques_required_level_nonneg",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterSystem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("level", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_systems",
                        to="adventures.adventure",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_systems",
                        to="adventures.character",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_systems",
                        to="adventures.skillsystem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure"], name="idx_character_systems_adv"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("adventure", "character", "system"),
                        name="uq_character_system",
                    ),
                    models.CheckConstraint(
                        condition=Q(("level__gte", 0)),
                        name="character_system_level_nonneg",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterTechnique",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("learned_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_techniques",
                        to="adventures.adventure",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_techniques",
                        to="adventures.character",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_techniques",
                        to="adventures.technique",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure"], name="idx_character_techniques_adv"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("adventure", "character", "technique"),
                        name="uq_character_technique",
                    ),
                ],
            },
        ),
        migrations.RunSQL(NEW_TRIGGERS_SQL, REVERSE_NEW_TRIGGERS_SQL),
    ]
