# Generated by Django 6.0 on 2025-12-23 05:45

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0003_skill_systems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="tier",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveConstraint(
            model_name="technique",
            name="techniques_tier_nonneg",
        ),
        migrations.AddConstraint(
            model_name="technique",
            constraint=models.CheckConstraint(
                condition=Q(("tier__gte", 0)) | Q(("tier__isnull", True)),
                name="techniques_tier_nonneg",
            ),
        ),
    ]
