# Generated by Django 6.0 on 2025-12-23 06:20

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0004_technique_rank_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersystem",
            name="progress_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="charactersystem",
            constraint=models.CheckConstraint(
                condition=Q(("progress_percent__gte", 0)) & Q(("progress_percent__lte", 100)),
                name="character_system_progress_pct",
            ),
        ),
    ]
