# Generated by Django 6.0 on 2025-12-23 06:35

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0005_character_system_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdventureEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.TextField(choices=[("inactive", "inactive"), ("active", "active"), ("resolved", "resolved")], default="inactive")),
                ("title", models.TextField()),
                ("trigger_hint", models.TextField(blank=True)),
                ("active_summary", models.TextField(blank=True)),
                ("resolution_summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="adventures.adventure",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="adventures.location",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure", "status"], name="idx_events_adv_status"),
                    models.Index(fields=["adventure", "location", "status"], name="idx_events_adv_loc_status"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(("status__in", ["inactive", "active", "resolved"])),
                        name="events_status_chk",
                    )
                ],
            },
        ),
    ]
