# Generated by Django 6.0 on 2025-12-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0006_adventure_events"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adventureevent",
            name="active_summary",
        ),
        migrations.RemoveField(
            model_name="adventureevent",
            name="resolution_summary",
        ),
        migrations.RemoveField(
            model_name="adventureevent",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="adventureevent",
            name="last_observed_at",
        ),
        migrations.AddField(
            model_name="adventureevent",
            name="state",
            field=models.TextField(blank=True),
        ),
    ]
