# Generated by Django 6.0 on 2025-12-23 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0007_event_state_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventure",
            name="primary_hero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_in_adventures",
                to="adventures.character",
            ),
        ),
    ]
