# Generated by Django 6.0 on 2025-12-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0008_adventure_primary_hero"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="life_span",
            field=models.IntegerField(default=100),
        ),
    ]
