# Generated by Django 6.0 on 2025-12-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0009_race_life_span"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdventureHeroSetup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("require_race", models.BooleanField(default=True)),
                ("require_age", models.BooleanField(default=False)),
                ("require_body_power", models.BooleanField(default=True)),
                ("require_mind_power", models.BooleanField(default=True)),
                ("require_will_power", models.BooleanField(default=True)),
                ("require_systems", models.BooleanField(default=False)),
                ("require_techniques", models.BooleanField(default=False)),
                (
                    "adventure",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_setup",
                        to="adventures.adventure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["adventure"], name="idx_hero_setup_adv"),
                ],
            },
        ),
    ]
