# Generated by Django 6.0 on 2025-12-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0016_character_stat_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationEntry',
            fields=[
                ('adventure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, related_name='moderation_entry', to='adventures.adventure')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublishedAdventure',
            fields=[
                ('adventure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, related_name='publication_entry', to='adventures.adventure')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
