# Generated by Django 6.0 on 2026-04-22 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0025_multi_primary_heroes_npc_slots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ru', 'ru'), ('en', 'en'), ('zh-CN', 'zh-CN')], default='ru', max_length=8)),
                ('simple_language', models.BooleanField(default=False)),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduced_text_length', models.BooleanField(default=False)),
                ('choice_cards_enabled', models.BooleanField(default=True)),
                ('content_warnings_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_band', models.CharField(choices=[('15-18', '15-18'), ('18+', '18+')], default='15-18', max_length=16)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('competency', models.TextField(choices=[('empathy', 'empathy'), ('cooperation', 'cooperation'), ('self_regulation', 'self_regulation'), ('responsible_decision', 'responsible_decision'), ('restorative_action', 'restorative_action'), ('help_seeking', 'help_seeking'), ('inclusion', 'inclusion')])),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='adventures.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='PedagogicalIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dilemma', 'dilemma'), ('repair', 'repair'), ('perspective', 'perspective'), ('choice_cards', 'choice_cards')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogical_interventions', to='adventures.adventure')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='adventures.learningobjective')),
            ],
        ),
        migrations.CreateModel(
            name='ReflectionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_kind', models.CharField(choices=[('user_turn', 'user_turn'), ('ai_turn', 'ai_turn'), ('key_choice', 'key_choice')], default='key_choice', max_length=32)),
                ('question', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_prompts', to='adventures.adventure')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_prompts', to='adventures.learningobjective')),
            ],
        ),
        migrations.CreateModel(
            name='ReflectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_responses', to='adventures.adventure')),
                ('history_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflection_responses', to='adventures.adventurehistory')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='adventures.reflectionprompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.TextField(choices=[('empathy', 'empathy'), ('cooperation', 'cooperation'), ('self_regulation', 'self_regulation'), ('responsible_decision', 'responsible_decision'), ('restorative_action', 'restorative_action'), ('help_seeking', 'help_seeking'), ('inclusion', 'inclusion')])),
                ('marker', models.CharField(max_length=128)),
                ('score', models.SmallIntegerField(default=0)),
                ('confidence', models.FloatField(default=0.5)),
                ('excerpt', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_evidence', to='adventures.adventure')),
                ('history_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_evidence', to='adventures.adventurehistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_evidence', to=settings.AUTH_USER_MODEL)),
                ('reflection_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_evidence', to='adventures.reflectionresponse')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('risk_level', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=16)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('action', models.CharField(choices=[('allow', 'allow'), ('warn', 'warn'), ('block', 'block')], default='allow', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reviews', to='adventures.adventure')),
                ('history_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reviews', to='adventures.adventurehistory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='learningobjective',
            index=models.Index(fields=['adventure', 'is_active'], name='idx_learning_obj_active'),
        ),
        migrations.AddIndex(
            model_name='learningobjective',
            index=models.Index(fields=['competency'], name='idx_learning_obj_competency'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(fields=('adventure', 'code'), name='uq_learning_objective_code'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.CheckConstraint(condition=models.Q(('competency__in', ['empathy', 'cooperation', 'self_regulation', 'responsible_decision', 'restorative_action', 'help_seeking', 'inclusion'])), name='learning_objective_competency_chk'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 1), ('weight__lte', 5)), name='learning_objective_weight_range'),
        ),
        migrations.AddIndex(
            model_name='pedagogicalintervention',
            index=models.Index(fields=['adventure', 'kind', 'is_active'], name='idx_intervention_kind'),
        ),
        migrations.AddIndex(
            model_name='reflectionprompt',
            index=models.Index(fields=['adventure', 'is_active'], name='idx_reflection_active'),
        ),
        migrations.AddIndex(
            model_name='reflectionresponse',
            index=models.Index(fields=['adventure', 'user', '-created_at'], name='idx_reflection_user'),
        ),
        migrations.AddIndex(
            model_name='behaviorevidence',
            index=models.Index(fields=['adventure', 'user', '-created_at'], name='idx_evidence_user'),
        ),
        migrations.AddIndex(
            model_name='behaviorevidence',
            index=models.Index(fields=['competency'], name='idx_evidence_competency'),
        ),
        migrations.AddConstraint(
            model_name='behaviorevidence',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', -2), ('score__lte', 2)), name='behavior_evidence_score_range'),
        ),
        migrations.AddConstraint(
            model_name='behaviorevidence',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='behavior_evidence_confidence_range'),
        ),
        migrations.AddIndex(
            model_name='safetyreview',
            index=models.Index(fields=['adventure', '-created_at'], name='idx_safety_adventure'),
        ),
        migrations.AddIndex(
            model_name='safetyreview',
            index=models.Index(fields=['risk_level', 'action'], name='idx_safety_risk_action'),
        ),
    ]
