# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0026_accessibilityprofile_learnerprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventure",
            name="story_simple_language",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adventure",
            name="story_reduced_text_length",
            field=models.BooleanField(default=False),
        ),
    ]
