# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0027_adventure_story_accessibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventure",
            name="facilitator_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
