# Generated by Django 6.0 on 2026-05-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0029_consequencemarker_repairopportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='growth_analysis_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventure',
            name='narrative_consequences_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NarrativeConsequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('active', 'active'), ('resolved', 'resolved'), ('archived', 'archived')], default='active', max_length=16)),
                ('importance', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_consequences', to='adventures.adventure')),
                ('source_history_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrative_consequences', to='adventures.adventurehistory')),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeConsequenceCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_consequence_links', to='adventures.character')),
                ('consequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='adventures.narrativeconsequence')),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeConsequenceFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_links', to='adventures.narrativeconsequence')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_consequence_links', to='adventures.faction')),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeConsequenceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_links', to='adventures.narrativeconsequence')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_consequence_links', to='adventures.location')),
            ],
        ),
        migrations.AddIndex(
            model_name='narrativeconsequence',
            index=models.Index(fields=['adventure', 'status', '-importance', '-updated_at'], name='idx_narrative_conseq_active'),
        ),
        migrations.AddConstraint(
            model_name='narrativeconsequence',
            constraint=models.CheckConstraint(condition=models.Q(('importance__gte', 1), ('importance__lte', 5)), name='narrative_consequence_importance_range'),
        ),
        migrations.AddIndex(
            model_name='narrativeconsequencecharacter',
            index=models.Index(fields=['character'], name='idx_narrative_conseq_char'),
        ),
        migrations.AddConstraint(
            model_name='narrativeconsequencecharacter',
            constraint=models.UniqueConstraint(fields=('consequence', 'character'), name='uq_narrative_conseq_character'),
        ),
        migrations.AddIndex(
            model_name='narrativeconsequencefaction',
            index=models.Index(fields=['faction'], name='idx_narrative_conseq_faction'),
        ),
        migrations.AddConstraint(
            model_name='narrativeconsequencefaction',
            constraint=models.UniqueConstraint(fields=('consequence', 'faction'), name='uq_narrative_conseq_faction'),
        ),
        migrations.AddIndex(
            model_name='narrativeconsequencelocation',
            index=models.Index(fields=['location'], name='idx_narrative_conseq_loc'),
        ),
        migrations.AddConstraint(
            model_name='narrativeconsequencelocation',
            constraint=models.UniqueConstraint(fields=('consequence', 'location'), name='uq_narrative_conseq_location'),
        ),
    ]
